In [1]:
import netCDF4 as nc
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Setting up the variables and dataset
fn = 'Data.nc'
data = xr.open_dataset(fn)
SM = data['SoilMoist_S_tavg']
Temp = data['AvgSurfT_tavg']
ET = data['Evap_tavg']
time = data['time']

In [3]:
# finding the 40th percentile of soil moisture at each raster
fourty_percentile = SM.quantile(0.4,dim='time')
fourty_percentile

C:\Users\I-SMART_Lab_03\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,


<xarray.DataArray 'SoilMoist_S_tavg' (lat: 38, lon: 41)>
array([[       nan,        nan,        nan, ..., 1.16405132, 1.18957272,
        1.01979418],
       [       nan,        nan,        nan, ..., 1.20828567, 0.99478111,
        0.99874672],
       [       nan,        nan,        nan, ..., 1.13843658, 1.15027957,
        1.19627891],
       ...,
       [       nan,        nan, 6.65389786, ..., 3.20984879, 3.1256825 ,
        3.0465672 ],
       [       nan,        nan, 6.65713224, ..., 3.27486   , 3.19038105,
        3.13392539],
       [       nan, 6.17374573, 6.59907417, ..., 3.42103744, 4.34405756,
        3.2912991 ]])
Coordinates:
  * lon       (lon) float32 -124.4 -124.1 -123.9 -123.6 ... -114.9 -114.6 -114.4
  * lat       (lat) float32 32.62 32.88 33.12 33.38 ... 41.12 41.38 41.62 41.88
    quantile  float64 0.4

In [4]:
# checking whether the soil moisture value at each raster is less than the 40th percentile value we calculated above
SM_percentile_truth = SM<fourty_percentile
SM_percentile_truth

<xarray.DataArray 'SoilMoist_S_tavg' (time: 6909, lat: 38, lon: 41)>
array([[[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
...
        ...,
        [False, False, False, ...,  True,  True, False],
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ...,  True,  True, False],
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ...,  True,  True, False],
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True]]])
Coordinates:
  * time      (time) datetime64[ns] 2003-02-01 2003-02-02 ... 2021-12-31
  * lon       (lon) float32 -124.4 -124.1 -123.9 -123.6 ... -114.9 -114.6 -114.4
  * lat       (lat) float32 32.62 32.88 33.12 33.38 ... 41.12 41.38 41.62 41.88
    quantile  float64 0.4

In [55]:
# finding the monthly means for temperature
Temp_monthly_means = Temp.groupby("time.month").mean("time")
Temp_monthly_means

<xarray.DataArray 'AvgSurfT_tavg' (month: 12, lat: 38, lon: 41)>
array([[[      nan,       nan,       nan, ..., 287.18106, 287.28433,
         286.83957],
        [      nan,       nan,       nan, ..., 286.36993, 287.04443,
         287.42578],
        [      nan,       nan,       nan, ..., 285.18097, 286.19876,
         285.74258],
        ...,
        [      nan,       nan, 279.45288, ..., 267.16275, 268.95758,
         267.807  ],
        [      nan,       nan, 278.4344 , ..., 268.06015, 266.72507,
         268.11148],
        [      nan, 281.3445 , 278.49463, ..., 267.7651 , 268.99542,
         266.8237 ]],

       [[      nan,       nan,       nan, ..., 289.25247, 289.41656,
         289.12994],
        [      nan,       nan,       nan, ..., 288.36334, 289.2184 ,
         289.67535],
        [      nan,       nan,       nan, ..., 287.341  , 288.4233 ,
         287.87723],
...
        [      nan,       nan, 281.6959 , ..., 274.3041 , 275.2881 ,
         274.90292],
        [      nan,       nan, 280.67175, ..., 274.65585, 274.0166 ,
         274.9572 ],
        [      nan, 283.245  , 280.75476, ..., 274.17932, 274.97885,
         273.79358]],

       [[      nan,       nan,       nan, ..., 286.77588, 286.84604,
         286.43396],
        [      nan,       nan,       nan, ..., 285.9122 , 286.57108,
         286.95535],
        [      nan,       nan,       nan, ..., 284.71982, 285.70667,
         285.25397],
        ...,
        [      nan,       nan, 279.10406, ..., 268.63687, 269.84818,
         269.21118],
        [      nan,       nan, 278.06754, ..., 269.2171 , 268.3592 ,
         269.40002],
        [      nan, 281.10184, 278.09064, ..., 268.7843 , 269.7137 ,
         268.18863]]], dtype=float32)
Coordinates:
  * lon      (lon) float32 -124.4 -124.1 -123.9 -123.6 ... -114.9 -114.6 -114.4
  * lat      (lat) float32 32.62 32.88 33.12 33.38 ... 41.12 41.38 41.62 41.88
  * month    (month) int64 1 2 3 4 5 6 7 8 9 10 11 12

In [64]:
# testing the temp monthly means at a specific point to see if the anomaly is actually being calculated based on the monthly mean
specific_point = Temp_monthly_means.sel(lat=36.125,lon=-121.125)
specific_point

<xarray.DataArray 'AvgSurfT_tavg' (month: 12)>
array([282.39084, 282.9675 , 284.69934, 286.79   , 290.22342, 294.43936,
       297.56686, 297.08908, 295.28436, 290.7192 , 285.69006, 282.14163],
      dtype=float32)
Coordinates:
    lon      float32 -121.1
    lat      float32 36.12
  * month    (month) int64 1 2 3 4 5 6 7 8 9 10 11 12

In [65]:
# testing the temp monthly means at a specific point to see if the anomaly is actually being calculated based on the monthly mean
anom = Temp.groupby("time.month") - Temp_monthly_means
anom.sel(lat=36.125,lon=-121.125)

<xarray.DataArray 'AvgSurfT_tavg' (time: 6909)>
array([ 2.9035034 ,  0.04205322, -1.649231  , ..., -2.1140442 ,
       -0.82418823, -2.5451355 ], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 2003-02-01 2003-02-02 ... 2021-12-31
    lon      float32 -121.1
    lat      float32 36.12
    month    (time) int64 2 2 2 2 2 2 2 2 2 2 ... 12 12 12 12 12 12 12 12 12 12

In [66]:
# testing the temp monthly means at a specific point to see if the anomaly is actually being calculated based on the monthly mean
Temp.sel(lat=36.125,lon=-121.125)

<xarray.DataArray 'AvgSurfT_tavg' (time: 6909)>
array([285.871  , 283.00955, 281.31827, ..., 280.0276 , 281.31744, 279.5965 ],
      dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 2003-02-01 2003-02-02 ... 2021-12-31
    lon      float32 -121.1
    lat      float32 36.12
Attributes:
    standard_name:  surface_temperature
    long_name:      Average Surface Skin temperature
    units:          K
    cell_methods:   time: mean
    vmin:           214.4687
    vmax:           312.36307

In [ ]:
# After manually using a calculator by checking the first and last values of the array 
# I can conclude that the anomalies are being correctly calculated based on monthly means

In [70]:
temp_monthly_std = Temp.groupby("time.month").std("time")
temp_monthly_std

<xarray.DataArray 'AvgSurfT_tavg' (month: 12, lat: 38, lon: 41)>
array([[[      nan,       nan,       nan, ..., 2.8316388, 2.855327 ,
         2.834765 ],
        [      nan,       nan,       nan, ..., 2.9140632, 2.9274812,
         2.9202347],
        [      nan,       nan,       nan, ..., 2.9581115, 2.9972377,
         3.0400288],
        ...,
        [      nan,       nan, 2.6807525, ..., 5.4375787, 4.733004 ,
         5.0646615],
        [      nan,       nan, 2.7897956, ..., 5.1214375, 5.404792 ,
         5.098192 ],
        [      nan, 2.4162405, 2.8584137, ..., 5.122837 , 4.838944 ,
         5.340461 ]],

       [[      nan,       nan,       nan, ..., 3.0290883, 3.0802317,
         3.0945191],
        [      nan,       nan,       nan, ..., 3.1051817, 3.1485128,
         3.1773722],
        [      nan,       nan,       nan, ..., 3.180362 , 3.2262237,
         3.2860818],
...
        [      nan,       nan, 2.8324215, ..., 4.207967 , 4.2755146,
         4.230003 ],
        [      nan,       nan, 2.975277 , ..., 4.236913 , 4.246837 ,
         4.2503505],
        [      nan, 2.4187438, 3.0564513, ..., 4.3446846, 4.32302  ,
         4.255142 ]],

       [[      nan,       nan,       nan, ..., 2.8309276, 2.8608074,
         2.8925111],
        [      nan,       nan,       nan, ..., 2.887169 , 2.910288 ,
         2.933744 ],
        [      nan,       nan,       nan, ..., 2.9366364, 2.9783711,
         3.04024  ],
        ...,
        [      nan,       nan, 2.9146717, ..., 4.4295855, 4.114141 ,
         4.1625957],
        [      nan,       nan, 2.9630263, ..., 4.3028173, 4.4278417,
         4.2153363],
        [      nan, 2.630715 , 3.0430965, ..., 4.362928 , 4.1982355,
         4.4856696]]], dtype=float32)
Coordinates:
  * lon      (lon) float32 -124.4 -124.1 -123.9 -123.6 ... -114.9 -114.6 -114.4
  * lat      (lat) float32 32.62 32.88 33.12 33.38 ... 41.12 41.38 41.62 41.88
  * month    (month) int64 1 2 3 4 5 6 7 8 9 10 11 12